#!/usr/bin/env bash

set -eu

PREFIX=refs/kv
FORTY_NOUGHTS=$(printf '%040d\n' 0)



warn() {
    local msg="$1"
    >&2 echo "${msg}"
}

# -- KV Store -- #

txn_begin() {
    local ns="$1"

    TXN_REF="${PREFIX}/${ns}"; export TXN_REF
    TXN_BASE=$(git rev-parse --verify -q "$TXN_REF" || true); export TXN_BASE
    GIT_INDEX_FILE=$(mktemp); export GIT_INDEX_FILE
    trap drop_index EXIT

    if [ -n "$TXN_BASE" ]; then
        git read-tree "$TXN_BASE"
    else
        git read-tree --empty
    fi
}

txn_commit () {
    local msg="$1"
    local base="$TXN_BASE"

    tree=$(git write-tree)
    commit=$(with-author git commit-tree "$tree" ${base:+-p "$base"} ${msg:+-m "$msg"})
    git update-ref "$TXN_REF" "$commit" "${base:-$FORTY_NOUGHTS}" 2>/dev/null

    unset TXN_BASE
    unset TXN_REF
}

with_author () {
    local name=${GIT_AUTHOR_NAME:-Git KV}
    local email=${GIT_AUTHOR_EMAIL:-kv@localhost}

    GIT_AUTHOR_NAME=${name} \
    GIT_AUTHOR_EMAIL=${email} \
    GIT_COMMITTER_NAME=${GIT_COMMITTER_NAME:-$name} \
    GIT_COMMITTER_EMAIL=${GIT_COMMITTER_EMAIL:-$email} \
    "$@"
}

kv_get() {
    local ns="$1"
    local key="$2"
    local ref="${PREFIX}/${ns}:keys/${key}"
    git cat-file -p "${ref}" 2>/dev/null
}

kv_set() {
    local ns="$1"
    local key="$2"
    local value="$3"

    local ref="${PREFIX}/${ns}"
    local base
    local hash

    txn_begin "$ns"

    hash=$(printf '%s' "$value" | git hash-object -w --stdin)
    git update-index --add --cacheinfo "100644,${hash},keys/${key}"

    txn_commit "kv: ${key} => ${value}"
}

kv_delete() {
    local ns="$1"
    local key="$2"

    txn_begin "$ns"

    git update-index --force-remove "keys/${key}"

    txn_commit "kv: ${key} => deleted"
}

kv_clear () {
    local ns="$1"

    txn_begin "$ns"

    git read-tree --empty

    txn_commit "kv: clear"
}

kv_log () {
    local ns="$1"
    git log "${PREFIX}/${ns}"
}

kv_keys() {
    local ns="$1"
    local ref="${PREFIX}/${ns}"

    git ls-tree --name-only "${ref}:keys"
}


drop_index() {
    if [ -n "${GIT_INDEX_FILE:-}" ]; then
        rm -f "$GIT_INDEX_FILE"
        unset GIT_INDEX_FILE
    fi
}

main () {
    local cmd="$1"; shift
    case "$cmd" in
        get)
            kv_get "$@"
            ;;
        set)
            kv_set "$@"
            ;;
        log)
            kv_log "$@"
            ;;
        *)
            echo "Usage: $0 <get|set> <namespace> <key> [value]"
            exit 1
    esac
}

main "$@"
